apiVersion: v1
kind: Service
metadata:
  name: guests
  labels:
    app: guests
spec:
  type: NodePort
  ports:
  - name: server
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: guests