apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guests-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guests
    spec:
      containers:
      - image: oblacki/guests:261217v2
        name: guests
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP